### ISSUE TITLE
Bullet bounce

### ISSUE THREAD

**Issue by ckawell** [OSUGameDev/GroupGame#25]
Details to be determined by developer.

**Comment by moorbren** [comment]
Current State: Bullet bouncing sort of works, there is some collision issue which prevents the bounce from always occurring.

**Comment by moorbren** [comment]
Bullet bouncing now works about 95% of the time, but has occasional instances where bullet goes through objects without bouncy.

**Comment by moorbren** [comment]
Bullet bouncing is finished for now, small modifications will be made if needed.
